# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_teacher_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='teacher', to='app.Course'),
        ),
    ]
