# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170106_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='index',
            field=models.CharField(default='', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
