# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select', to='app.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='training',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='training',
            name='course',
        ),
        migrations.RemoveField(
            model_name='training',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='time',
        ),
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.IntegerField(choices=[(1, '一对一教学'), (2, '自习'), (3, '一对一 + 自习')]),
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.AddField(
            model_name='courseselect',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select', to='app.Student'),
        ),
        migrations.AddField(
            model_name='courseselect',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select', to='app.Teacher'),
        ),
    ]
