# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_classrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='study_note',
            field=models.TextField(null=True),
        ),
    ]
