# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_classrecord_study_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='book',
            field=models.IntegerField(choices=[(1, '上册'), (2, '下册')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classrecord',
            name='unit',
            field=models.IntegerField(choices=[(1, '第一单元'), (2, '第二单元'), (3, '第三单元'), (4, '第四单元'), (5, '第五单元'), (6, '第六单元'), (7, '第七单元'), (8, '第八单元'), (9, '第九单元')], default=1),
            preserve_default=False,
        ),
    ]
