# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170107_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
