# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170109_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
