# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_teacher_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.IntegerField(choices=[(1, '小学'), (2, '初中'), (3, '高中')])),
                ('grade', models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级')])),
                ('course', models.IntegerField(choices=[(1, '语文'), (2, '数学'), (3, '外语'), (4, '物理'), (5, '化学'), (6, '生物')])),
                ('book', models.IntegerField(choices=[(1, '上册'), (2, '下册')])),
                ('unit', models.IntegerField(choices=[(1, '第一单元'), (2, '第二单元'), (3, '第三单元'), (4, '第四单元'), (5, '第五单元'), (6, '第六单元'), (7, '第七单元'), (8, '第八单元'), (9, '第九单元')])),
                ('note', models.TextField(null=True)),
                ('study', models.IntegerField(choices=[(1, '学习状态：学习状态不佳，注意力无法集中'), (2, '学习状态：刚开始上课注意力较为集中，但无法维持良好的学习状态，注意力分散较快'), (3, '学习状态：刚开始上课注意力不集中，但稍后就有改善。'), (4, '学习状态：注意力较为集中，学习状态不错')])),
                ('knowledge', models.IntegerField(choices=[(1, '知识接受情况：知识接受情况较差，听不进去课'), (2, '知识接受情况：知识接受情况较差，可以接受，但不能理解'), (3, '知识接受情况：知识接受情况良好，讲到的内容都可以接受')])),
                ('practice', models.IntegerField(choices=[(1, '练习反馈：练习表现较差，知识未能消化，还需要对知识点进行巩固复习和多加练习'), (2, '练习反馈：练习状况良好，但并未能完全掌握所学的内容，需要多加练习'), (3, '练习反馈：练习完成情况不错，能熟练的运用学到的知识')])),
                ('study_note', models.TextField(null=True)),
                ('date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='app.Teacher')),
            ],
        ),
    ]
